MODEL:
  TYPE: vssm
  NAME: vssm_tiny
  DROP_PATH_RATE: 0.2
  PRETRAIN_CKPT: "/kaggle/input/weight_mamba_unet/pytorch/default/1/vmamba_tiny_e292.pth"
  VSSM:
    EMBED_DIM: 96
    DEPTHS: [ 2, 2, 2, 2 ]
    PATCH_SIZE: 4
    IN_CHANS: 3